name: 'cyRating check'
inputs:
  access-token:
    description: 'Access token to authenticate usage'
    required: true
  secret-token:
    description: 'Secret token to authenticate usage'
    required: true
  cve:
    description: 'CVE to check'
    required: true
outputs:
  cy-rating:
    description: 'cyRating value for given CVE'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.access-token }}
    - ${{ inputs.secret-token }}
    - ${{ inputs.cve }}
